name: Bun Compile, Test, Build

on:
  push:
    branches:
      - bun

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/bun
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: oven-sh/setup-bun@v0.1.8
      - run: bun i
      - run: bun run typecheck
      - run: bun run test
      - uses: docker/build-push-action@v4
        with:
          push: true
          context: projects/bun
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/michalwarda/todo-benchmark/bun:latest