name: Bun Compile, Test, Build

on:
  push:
    branches:
      - main

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/bun
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v0.1.8
      - run: bun i
      - run: bun run test