name: Node Compile, Test, Build

on:
  push:
    branches:
      - main

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/node
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'pnpm'
          cache-dependency-path: projects/node/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm run test -- --run
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/michalwarda/todo-benchmark/node
          tags: |
            type=sha
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          context: projects/node
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}