name: Node Compile, Test, Build

on:
  push:
    branches:
      - main

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/node
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'pnpm'
          cache-dependency-path: projects/node/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm run test -- --run